# Generated by Django 3.0.7 on 2020-06-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0002_userextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
